#!/usr/bin/env python3
# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.
"""Generate the statuses reference page from the charm ``Status`` enum.

This script parses the ``Status`` enum in
``common/single_kernel_kafka/core/literals.py`` using the ``ast`` module
(not import — importing would trigger ``SUBSTRATE`` env-var logic, ``ops``
dependency, and ``refresh_versions.toml`` file reads).

For each enum member it extracts:

* the Juju status label (Active / Blocked / Waiting / Maintenance)
* the status message text (resolving f-string interpolations such as
  ``{SNAP_NAME}`` and ``{MIN_REPLICAS}`` by reading those module-level
  constants from the same AST)

It then merges manually-authored ``expectations`` and ``actions`` prose
from ``docs/_dev/statuses-manual.yaml``, keyed by enum member name.

The result is emitted as MyST Markdown into
``docs/reference/_generated/statuses.md`` (gitignored), following the
same pattern as ``generate_charm_reference.py``.

Usage::

    python3 docs/_dev/generate_statuses.py

Outputs::

    docs/reference/_generated/statuses.md
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path
from typing import Any

import yaml

# Resolve paths relative to this script so it works regardless of CWD.
# Script:  docs/_dev/generate_statuses.py
# Docs:    docs/
# Repo:    (root)
_SCRIPT_PATH = Path(__file__).resolve()
_DEV_DIR = _SCRIPT_PATH.parent
_DOCS_DIR = _DEV_DIR.parent
_REPO_ROOT = _DOCS_DIR.parent
_COMMON_DIR = _REPO_ROOT / "common"
_OUTPUT_DIR = _DOCS_DIR / "reference" / "_generated"

_LITERALS_FILE = _COMMON_DIR / "single_kernel_kafka" / "core" / "literals.py"
_MANUAL_FILE = _DEV_DIR / "statuses-manual.yaml"

_AUTOGEN_NOTICE = (
    "<!-- AUTO-GENERATED. Do not edit this file directly. "
    "Edit common/single_kernel_kafka/core/literals.py and/or "
    "docs/_dev/statuses-manual.yaml and rebuild. -->"
)

# Map ops status class name -> Juju status label shown in the table.
_STATUS_LABEL: dict[str, str] = {
    "ActiveStatus": "Active",
    "BlockedStatus": "Blocked",
    "WaitingStatus": "Waiting",
    "MaintenanceStatus": "Maintenance",
    "ErrorStatus": "Error",
}


# ---------------------------------------------------------------------------
# AST parsing
# ---------------------------------------------------------------------------


def _resolve_constant(tree: ast.AST, name: str) -> Any:
    """Return the value of a module-level assignment ``name = <literal>``.

    Supports simple literals (str, int) and conditional assignments where
    the last branch wins (e.g. ``SNAP_NAME`` is reassigned inside an
    ``if`` block).  Returns ``None`` if the name is not found.
    """
    value: Any = None
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == name:
                    if isinstance(node.value, ast.Constant):
                        value = node.value.value
    return value


def _eval_joinedstr(node: ast.JoinedStr, constants: dict[str, Any]) -> str:
    """Evaluate an ``ast.JoinedStr`` (f-string) to a plain string.

    ``constants`` maps variable names to their resolved values.  Only
    simple ``{name}`` interpolations are supported — no arbitrary
    expressions.
    """
    parts: list[str] = []
    for val in node.values:
        if isinstance(val, ast.Constant):
            parts.append(str(val.value))
        elif isinstance(val, ast.FormattedValue):
            inner = val.value
            if isinstance(inner, ast.Name) and inner.id in constants:
                parts.append(str(constants[inner.id]))
            else:
                # Fallback: best-effort for unknown interpolations.
                parts.append(f"{{{ast.unparse(inner)}}}")
    return "".join(parts)


def parse_status_enum(path: Path) -> list[dict[str, str]]:
    """Parse the ``Status`` enum from ``literals.py`` via AST.

    Returns a list of ``{"name", "status_class", "message"}`` dicts in
    declaration order.  ``status_class`` is the raw ops class name
    (e.g. ``"BlockedStatus"``); the caller maps it to a label.
    """
    tree = ast.parse(path.read_text(encoding="utf-8"))

    # Resolve constants that may appear in f-string messages.
    snap_name = _resolve_constant(tree, "SNAP_NAME") or "charmed-kafka"
    min_replicas = _resolve_constant(tree, "MIN_REPLICAS") or 3
    constants: dict[str, Any] = {
        "SNAP_NAME": snap_name,
        "MIN_REPLICAS": min_replicas,
    }

    statuses: list[dict[str, str]] = []

    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef) or node.name != "Status":
            continue
        for item in node.body:
            if not isinstance(item, ast.Assign):
                continue
            target = item.targets[0]
            if not isinstance(target, ast.Name):
                continue
            member_name = target.id

            # item.value is a Call to StatusLevel(<status_obj>, "LEVEL")
            call = item.value
            if not isinstance(call, ast.Call):
                continue
            status_arg = call.args[0] if call.args else None
            if not isinstance(status_arg, ast.Call):
                continue

            status_class = (
                status_arg.func.id
                if isinstance(status_arg.func, ast.Name)
                else None
            ) or ""

            # Extract message: first positional arg to the status class.
            message = ""
            if status_arg.args:
                msg_node = status_arg.args[0]
                if isinstance(msg_node, ast.Constant):
                    message = str(msg_node.value) if msg_node.value is not None else ""
                elif isinstance(msg_node, ast.JoinedStr):
                    message = _eval_joinedstr(msg_node, constants)

            statuses.append(
                {
                    "name": member_name,
                    "status_class": status_class,
                    "message": message,
                }
            )
        break  # only the Status enum

    return statuses


# ---------------------------------------------------------------------------
# Markdown rendering
# ---------------------------------------------------------------------------


def _render_front_matter(description: str) -> list[str]:
    """Return the YAML front matter lines for the generated page."""
    return [
        "---",
        "myst:",
        "  html_meta:",
        f'    description: "{description}"',
        "---",
        "",
    ]


def _escape_cell(text: str) -> str:
    """Escape pipe characters and collapse whitespace for a table cell."""
    if not text:
        return ""
    return " ".join(text.split()).replace("|", "\\|")


def generate_statuses_page(
    enum_statuses: list[dict[str, str]],
    manual: dict[str, Any],
) -> str:
    """Render the statuses reference page as MyST Markdown.

    Parameters
    ----------
    enum_statuses
        Parsed ``Status`` enum members (name, status_class, message).
    manual
        Parsed ``statuses-manual.yaml`` content with ``statuses`` and
        ``framework`` sections.
    """
    manual_statuses: dict[str, Any] = manual.get("statuses", {}) or {}
    framework_statuses: list[dict[str, Any]] = manual.get("framework", []) or []

    lines: list[str] = []
    lines.extend(
        _render_front_matter(
            "Charmed Apache Kafka charm statuses reference - complete guide "
            "to Juju application statuses, messages, and troubleshooting "
            "actions."
        )
    )
    lines.append(_AUTOGEN_NOTICE)
    lines.append("")
    lines.append("(reference-statuses)=")
    lines.append("# Charm statuses")
    lines.append("")
    lines.append(
        "A deployed charm follows [standard Juju applications statuses]"
        "(https://canonical.com/juju/docs/juju-cli/3.6/reference/status/"
        "#application-status). Here you can find the expected reactions on "
        "many typical Charmed Apache Kafka statuses:"
    )
    lines.append("")
    lines.append("| Juju Status | Message | Expectations | Actions |")
    lines.append("|---|---|---|---|")

    n_shown = 0
    n_hidden = 0

    for s in enum_statuses:
        member_name = s["name"]
        manual_entry = manual_statuses.get(member_name)

        # Skip hidden statuses.
        if manual_entry and manual_entry.get("hidden"):
            n_hidden += 1
            continue

        label = _STATUS_LABEL.get(s["status_class"], s["status_class"] or "")
        message = _escape_cell(s["message"])
        expectations = ""
        actions = ""
        if manual_entry:
            expectations = _escape_cell(str(manual_entry.get("expectations", "")))
            actions = _escape_cell(str(manual_entry.get("actions", "")))

        lines.append(f"| {label} | {message} | {expectations} | {actions} |")
        n_shown += 1

    # Framework-level statuses (Terminated, Unknown, Error, …).
    n_framework = 0
    for fw in framework_statuses:
        label = str(fw.get("status", ""))
        message = _escape_cell(str(fw.get("message", "")))
        expectations = _escape_cell(str(fw.get("expectations", "")))
        actions = _escape_cell(str(fw.get("actions", "")))
        lines.append(f"| {label} | {message} | {expectations} | {actions} |")
        n_framework += 1

    lines.append("")
    lines.append(
        "This page is generated at build time from "
        "[`common/single_kernel_kafka/core/literals.py`]"
        "(https://github.com/canonical/kafka-operator/blob/main/common/"
        "single_kernel_kafka/core/literals.py) and "
        "[`docs/_dev/statuses-manual.yaml`]"
        "(https://github.com/canonical/kafka-operator/blob/main/docs/"
        "_dev/statuses-manual.yaml)."
    )
    lines.append("")

    return "\n".join(lines) + "\n", n_shown, n_hidden, n_framework


# ---------------------------------------------------------------------------
# Validation warnings
# ---------------------------------------------------------------------------


def _warn_orphans(
    enum_names: set[str], manual_statuses: dict[str, Any]
) -> int:
    """Warn about manual entries whose key doesn't match any enum member."""
    n = 0
    for key in manual_statuses:
        if key not in enum_names:
            print(
                f"WARNING: manual entry '{key}' does not match any Status "
                f"enum member — stale or orphaned.",
                file=sys.stderr,
            )
            n += 1
    return n


def _warn_undocumented(
    enum_names: set[str], manual_statuses: dict[str, Any]
) -> int:
    """Warn about enum members with no manual entry (not even hidden)."""
    n = 0
    for name in enum_names:
        if name not in manual_statuses:
            print(
                f"WARNING: Status enum member '{name}' has no manual entry "
                f"— will appear with empty Expectations/Actions.",
                file=sys.stderr,
            )
            n += 1
    return n


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    """Generate the statuses reference page.

    Returns 0 on success, 1 if a source file is missing.
    """
    if not _LITERALS_FILE.exists():
        print(f"ERROR: literals file not found: {_LITERALS_FILE}", file=sys.stderr)
        return 1
    if not _MANUAL_FILE.exists():
        print(f"ERROR: manual file not found: {_MANUAL_FILE}", file=sys.stderr)
        return 1

    enum_statuses = parse_status_enum(_LITERALS_FILE)
    with _MANUAL_FILE.open(encoding="utf-8") as fh:
        manual = yaml.safe_load(fh) or {}

    manual_statuses: dict[str, Any] = manual.get("statuses", {}) or {}

    # Validation warnings (non-fatal).
    enum_names = {s["name"] for s in enum_statuses}
    _warn_orphans(enum_names, manual_statuses)
    _warn_undocumented(enum_names, manual_statuses)

    _OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    page, n_shown, n_hidden, n_framework = generate_statuses_page(
        enum_statuses, manual
    )
    out = _OUTPUT_DIR / "statuses.md"
    out.write_text(page, encoding="utf-8")

    print(
        f"Generated {out.relative_to(_REPO_ROOT)} "
        f"({n_shown} shown, {n_hidden} hidden, {n_framework} framework)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
