#!/usr/bin/env python3
# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.
"""Generate the statuses reference page from the charm ``Status`` enum.

This script parses the ``Status`` enum in
``common/single_kernel_kafka/core/literals.py`` using the ``ast`` module
(not import — importing would trigger ``SUBSTRATE`` env-var logic, ``ops``
dependency, and ``refresh_versions.toml`` file reads).

For each enum member it extracts:

* the Juju status label (Active / Blocked / Waiting / Maintenance)
* the status message text (resolving f-string interpolations such as
  ``{SNAP_NAME}`` and ``{MIN_REPLICAS}`` by reading those module-level
  constants from the same AST)
* the documentation prose (``expectations`` and ``actions``) from
  ``# docs:`` comments placed immediately after each enum member

The ``# docs:`` comments are NOT runtime data — they are documentation
prose consumed only by this script.  Recognised prefixes:

* ``# docs:expectations:`` — what this status means to the operator
* ``# docs:actions:``      — what the operator should do about it
* ``# docs:hidden``        — suppress this status from the docs table

Framework-level statuses (Maintenance/Error/Terminated/Unknown) are set
by Juju itself, not by charm code, so they are not in the enum.  They
are defined in ``_FRAMEWORK_STATUSES`` below and appended after the
enum-derived rows.

The result is emitted as MyST Markdown into
``docs/reference/_generated/statuses.md`` (gitignored).

Usage::

    python3 docs/_dev/generate_statuses.py

Outputs::

    docs/reference/_generated/statuses.md
"""

from __future__ import annotations

import ast
import io
import sys
import tokenize
from pathlib import Path
from typing import Any

# Expected script path:  docs/_dev/generate_statuses.py
_SCRIPT_PATH = Path(__file__).resolve()
_DEV_DIR = _SCRIPT_PATH.parent
_DOCS_DIR = _DEV_DIR.parent
_REPO_ROOT = _DOCS_DIR.parent
_COMMON_DIR = _REPO_ROOT / "common"
_OUTPUT_DIR = _DOCS_DIR / "reference" / "_generated"

_LITERALS_FILE = _COMMON_DIR / "single_kernel_kafka" / "core" / "literals.py"

_AUTOGEN_NOTICE = (
    "<!-- AUTO-GENERATED. Do not edit this file directly. "
    "Edit common/single_kernel_kafka/core/literals.py and rebuild. -->"
)

# Map ops status class name -> Juju status label shown in the table.
_STATUS_LABEL: dict[str, str] = {
    "ActiveStatus": "Active",
    "BlockedStatus": "Blocked",
    "WaitingStatus": "Waiting",
    "MaintenanceStatus": "Maintenance",
    "ErrorStatus": "Error",
}

# Framework-level statuses set by Juju itself, not by charm code.
_FRAMEWORK_STATUSES: list[dict[str, str]] = [
    {
        "status": "Maintenance",
        "message": "",
        "expectations": (
            "Charm is performing the internal maintenance (e.g. cluster "
            "re-configuration, upgrade, …)"
        ),
        "actions": "No actions required",
    },
    {
        "status": "Error",
        "message": "any",
        "expectations": "An unhandled internal error happened",
        "actions": (
            "Read the message hint. Execute Juju resolve <error_unit/0> "
            "after addressing the root of the error state"
        ),
    },
    {
        "status": "Terminated",
        "message": "any",
        "expectations": "The unit is gone and will be cleaned by Juju soon",
        "actions": "No actions possible",
    },
    {
        "status": "Unknown",
        "message": "any",
        "expectations": (
            "Juju doesn't know the charm app/unit status. Possible reason: "
            "K8s charm termination in progress."
        ),
        "actions": "Manual investigation required if status is permanent",
    },
]


# ---------------------------------------------------------------------------
# Comment parsing
# ---------------------------------------------------------------------------

# Prefixes used in literals.py to mark documentation prose.
_DOCS_EXPECTATIONS = "# docs:expectations:"
_DOCS_ACTIONS = "# docs:actions:"
_DOCS_HIDDEN = "# docs:hidden"


def parse_docs_comments(source: str) -> dict[int, dict[str, Any]]:
    """Parse ``# docs:`` comments from source via ``tokenize``.

    Returns a dict mapping the **line number of the enum member
    assignment** (the line *before* the first comment) to a dict with
    keys ``expectations``, ``actions``, and ``hidden``.

    Comments are grouped by proximity: consecutive comment lines
    immediately following an enum member are attached to that member.
    The key is the line number of the last non-comment, non-blank line
    before the comment block starts.
    """
    tokens = tokenize.generate_tokens(io.StringIO(source).readline)
    comments: list[tuple[int, str]] = []  # (line_no, comment_text)
    for tok in tokens:
        if tok.type == tokenize.COMMENT:
            text = tok.string
            if text.startswith(_DOCS_EXPECTATIONS) or text.startswith(
                _DOCS_ACTIONS
            ) or text.startswith(_DOCS_HIDDEN):
                comments.append((tok.start[0], text))

    if not comments:
        return {}

    # Read all lines so we can find the preceding non-comment line.
    lines = source.splitlines()

    result: dict[int, dict[str, Any]] = {}
    current_group: list[tuple[int, str]] = []
    prev_anchor_line = 0

    def _flush_group(group: list[tuple[int, str]], anchor: int) -> None:
        if not group or not anchor:
            return
        entry: dict[str, Any] = {
            "expectations": "",
            "actions": "",
            "hidden": False,
        }
        for _line, text in group:
            if text.startswith(_DOCS_EXPECTATIONS):
                entry["expectations"] += text[len(_DOCS_EXPECTATIONS) :].strip() + " "
            elif text.startswith(_DOCS_ACTIONS):
                entry["actions"] += text[len(_DOCS_ACTIONS) :].strip() + " "
            elif text.startswith(_DOCS_HIDDEN):
                entry["hidden"] = True
        entry["expectations"] = entry["expectations"].strip()
        entry["actions"] = entry["actions"].strip()
        result[anchor] = entry

    for line_no, text in comments:
        # If there's a gap (blank or non-comment line) since the last
        # comment, flush the current group and find a new anchor.
        if current_group and line_no != current_group[-1][0] + 1:
            _flush_group(current_group, prev_anchor_line)
            current_group = []

        if not current_group:
            # Find the preceding non-comment, non-blank line as anchor.
            for ln in range(line_no - 1, 0, -1):
                line = lines[ln - 1].strip() if ln - 1 < len(lines) else ""
                if line and not line.startswith("#"):
                    prev_anchor_line = ln
                    break

        current_group.append((line_no, text))

    _flush_group(current_group, prev_anchor_line)
    return result


# ---------------------------------------------------------------------------
# AST parsing
# ---------------------------------------------------------------------------


def _resolve_constant(tree: ast.AST, name: str) -> Any:
    """Return the value of a module-level assignment ``name = <literal>``.

    Supports simple literals (str, int) and conditional assignments where
    the last branch wins (e.g. ``SNAP_NAME`` is reassigned inside an
    ``if`` block).  Returns ``None`` if the name is not found.
    """
    value: Any = None
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == name:
                    if isinstance(node.value, ast.Constant):
                        value = node.value.value
    return value


def _eval_joinedstr(node: ast.JoinedStr, constants: dict[str, Any]) -> str:
    """Evaluate an ``ast.JoinedStr`` (f-string) to a plain string.

    ``constants`` maps variable names to their resolved values.  Only
    simple ``{name}`` interpolations are supported — no arbitrary
    expressions.
    """
    parts: list[str] = []
    for val in node.values:
        if isinstance(val, ast.Constant):
            parts.append(str(val.value))
        elif isinstance(val, ast.FormattedValue):
            inner = val.value
            if isinstance(inner, ast.Name) and inner.id in constants:
                parts.append(str(constants[inner.id]))
            else:
                # Fallback: best-effort for unknown interpolations.
                parts.append(f"{{{ast.unparse(inner)}}}")
    return "".join(parts)


def parse_status_enum(path: Path) -> list[dict[str, Any]]:
    """Parse the ``Status`` enum from ``literals.py`` via AST.

    Returns a list of dicts in declaration order, each with keys:
    ``name``, ``status_class``, ``message``, ``expectations``,
    ``actions``, ``hidden``.

    ``status_class`` is the raw ops class name (e.g.
    ``"BlockedStatus"``); the caller maps it to a label.
    """
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source)

    # Resolve constants that may appear in f-string messages.
    snap_name = _resolve_constant(tree, "SNAP_NAME") or "charmed-kafka"
    min_replicas = _resolve_constant(tree, "MIN_REPLICAS") or 3
    constants: dict[str, Any] = {
        "SNAP_NAME": snap_name,
        "MIN_REPLICAS": min_replicas,
    }

    # Parse # docs: comments, keyed by the line number of the enum
    # member assignment.
    docs_by_line = parse_docs_comments(source)

    statuses: list[dict[str, Any]] = []

    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef) or node.name != "Status":
            continue
        for item in node.body:
            if not isinstance(item, ast.Assign):
                continue
            target = item.targets[0]
            if not isinstance(target, ast.Name):
                continue
            member_name = target.id

            # item.value is a Call to StatusLevel(<status_obj>, "LEVEL")
            call = item.value
            if not isinstance(call, ast.Call):
                continue
            status_arg = call.args[0] if call.args else None
            if not isinstance(status_arg, ast.Call):
                continue

            status_class = (
                status_arg.func.id
                if isinstance(status_arg.func, ast.Name)
                else None
            ) or ""

            # Extract message: first positional arg to the status class.
            message = ""
            if status_arg.args:
                msg_node = status_arg.args[0]
                if isinstance(msg_node, ast.Constant):
                    message = (
                        str(msg_node.value)
                        if msg_node.value is not None
                        else ""
                    )
                elif isinstance(msg_node, ast.JoinedStr):
                    message = _eval_joinedstr(msg_node, constants)

            # Look up docs by the line number of the last line of the
            # assignment (end_lineno), because # docs: comments come
            # immediately after the assignment — which may span multiple
            # lines.
            end_line = getattr(item, "end_lineno", item.lineno)
            docs = docs_by_line.get(end_line, {})

            statuses.append(
                {
                    "name": member_name,
                    "status_class": status_class,
                    "message": message,
                    "expectations": docs.get("expectations", ""),
                    "actions": docs.get("actions", ""),
                    "hidden": docs.get("hidden", False),
                }
            )
        break  # only the Status enum

    return statuses


# ---------------------------------------------------------------------------
# Markdown rendering
# ---------------------------------------------------------------------------


def _render_front_matter(description: str) -> list[str]:
    """Return the YAML front matter lines for the generated page."""
    return [
        "---",
        "myst:",
        "  html_meta:",
        f'    description: "{description}"',
        "---",
        "",
    ]


def _escape_cell(text: str) -> str:
    """Escape pipe characters and collapse whitespace for a table cell."""
    if not text:
        return ""
    return " ".join(text.split()).replace("|", "\\|")


def generate_statuses_page(
    enum_statuses: list[dict[str, Any]],
) -> tuple[str, int, int, int]:
    """Render the statuses reference page as MyST Markdown.

    Returns a tuple of (markdown, n_shown, n_hidden, n_framework).
    """
    lines: list[str] = []
    lines.extend(
        _render_front_matter(
            "Charmed Apache Kafka charm statuses reference - complete guide "
            "to Juju application statuses, messages, and troubleshooting "
            "actions."
        )
    )
    lines.append(_AUTOGEN_NOTICE)
    lines.append("")
    lines.append("(reference-statuses)=")
    lines.append("# Charm statuses")
    lines.append("")
    lines.append(
        "A deployed charm follows [standard Juju applications statuses]"
        "(https://canonical.com/juju/docs/juju-cli/3.6/reference/status/"
        "#application-status). Here you can find the expected reactions on "
        "many typical Charmed Apache Kafka statuses:"
    )
    lines.append("")
    lines.append("| Juju Status | Message | Expectations | Actions |")
    lines.append("|---|---|---|---|")

    n_shown = 0
    n_hidden = 0

    for s in enum_statuses:
        if s.get("hidden"):
            n_hidden += 1
            continue

        label = _STATUS_LABEL.get(s["status_class"], s["status_class"] or "")
        message = _escape_cell(s["message"])
        expectations = _escape_cell(s.get("expectations", ""))
        actions = _escape_cell(s.get("actions", ""))

        lines.append(f"| {label} | {message} | {expectations} | {actions} |")
        n_shown += 1

    # Framework-level statuses (Terminated, Unknown, Error, …).
    n_framework = 0
    for fw in _FRAMEWORK_STATUSES:
        label = str(fw.get("status", ""))
        message = _escape_cell(str(fw.get("message", "")))
        expectations = _escape_cell(str(fw.get("expectations", "")))
        actions = _escape_cell(str(fw.get("actions", "")))
        lines.append(f"| {label} | {message} | {expectations} | {actions} |")
        n_framework += 1

    lines.append("")
    lines.append(
        "This page is generated at build time from "
        "[`common/single_kernel_kafka/core/literals.py`]"
        "(https://github.com/canonical/kafka-operator/blob/main/common/"
        "single_kernel_kafka/core/literals.py)."
    )
    lines.append("")

    return "\n".join(lines) + "\n", n_shown, n_hidden, n_framework


# ---------------------------------------------------------------------------
# Validation warnings
# ---------------------------------------------------------------------------


def _warn_undocumented(enum_statuses: list[dict[str, Any]]) -> int:
    """Warn about enum members with no docs comments (not even hidden)."""
    n = 0
    for s in enum_statuses:
        if not s.get("hidden") and not s.get("expectations") and not s.get("actions"):
            print(
                f"WARNING: Status enum member '{s['name']}' has no "
                f"# docs: comments — will appear with empty "
                f"Expectations/Actions.",
                file=sys.stderr,
            )
            n += 1
    return n


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    """Generate the statuses reference page.

    Returns 0 on success, 1 if the source file is missing.
    """
    if not _LITERALS_FILE.exists():
        print(f"ERROR: literals file not found: {_LITERALS_FILE}", file=sys.stderr)
        return 1

    enum_statuses = parse_status_enum(_LITERALS_FILE)

    # Validation warnings (non-fatal).
    _warn_undocumented(enum_statuses)

    _OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    page, n_shown, n_hidden, n_framework = generate_statuses_page(enum_statuses)
    out = _OUTPUT_DIR / "statuses.md"
    out.write_text(page, encoding="utf-8")

    print(
        f"Generated {out.relative_to(_REPO_ROOT)} "
        f"({n_shown} shown, {n_hidden} hidden, {n_framework} framework)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
