#!/usr/bin/env python3
# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.
"""Generate the statuses reference page from the charm ``Status`` enum.

Imports the ``Status`` enum from
``common/single_kernel_kafka/core/literals.py`` and reads the
documentation prose (``expectations``, ``actions``) carried on each
``StatusLevel``.  Members with no ``expectations`` and no ``actions``
are automatically excluded from the generated table.

Framework-level statuses (Maintenance/Error/Terminated/Unknown) are set
by Juju itself and are defined in ``_FRAMEWORK_STATUSES`` below.

Usage::

    python3 docs/_dev/generate_statuses.py

Outputs::

    docs/reference/_generated/statuses.md
"""

from __future__ import annotations

import sys
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

_SCRIPT_PATH = Path(__file__).resolve()
_DEV_DIR = _SCRIPT_PATH.parent
_DOCS_DIR = _DEV_DIR.parent
_REPO_ROOT = _DOCS_DIR.parent
_COMMON_DIR = _REPO_ROOT / "common"
_OUTPUT_DIR = _DOCS_DIR / "reference" / "_generated"
_TEMPLATES_DIR = _DEV_DIR / "templates"

# ``common`` is a sibling directory, not an installed package, so it has
# to go on ``sys.path`` before importing from it. Installing it instead
# would drag ~40 charm runtime dependencies into the docs build.
sys.path.insert(0, str(_COMMON_DIR))

from single_kernel_kafka.core.literals import Status, StatusLevel  # noqa: E402

_AUTOGEN_NOTICE = (
    "<!-- AUTO-GENERATED. Do not edit this file directly. "
    "Edit common/single_kernel_kafka/core/literals.py and rebuild. -->"
)

_env = Environment(
    loader=FileSystemLoader(_TEMPLATES_DIR),
    keep_trailing_newline=True,
    trim_blocks=True,
    lstrip_blocks=True,
)

_STATUS_LABEL: dict[str, str] = {
    "ActiveStatus": "Active",
    "BlockedStatus": "Blocked",
    "WaitingStatus": "Waiting",
    "MaintenanceStatus": "Maintenance",
    "ErrorStatus": "Error",
}

_FRAMEWORK_STATUSES: list[dict[str, str]] = [
    {
        "status": "Maintenance",
        "message": "",
        "expectations": (
            "Charm is performing the internal maintenance (e.g. cluster "
            "re-configuration, upgrade, …)"
        ),
        "actions": "No actions required",
    },
    {
        "status": "Error",
        "message": "any",
        "expectations": "An unhandled internal error happened",
        "actions": (
            "Read the message hint. Execute Juju resolve <error_unit/0> "
            "after addressing the root of the error state"
        ),
    },
    {
        "status": "Terminated",
        "message": "any",
        "expectations": "The unit is gone and will be cleaned by Juju soon",
        "actions": "No actions possible",
    },
    {
        "status": "Unknown",
        "message": "any",
        "expectations": (
            "Juju doesn't know the charm app/unit status. Possible reason: "
            "K8s charm termination in progress."
        ),
        "actions": "Manual investigation required if status is permanent",
    },
]


def _escape_cell(text: str) -> str:
    """Escape pipe characters and collapse whitespace for a table cell."""
    if not text:
        return ""
    return " ".join(text.split()).replace("|", "\\|")


def _status_label(level: StatusLevel) -> str:
    """Map an ops status object to its Juju status label."""
    class_name = type(level.status).__name__
    return _STATUS_LABEL.get(class_name, class_name)


def _prepare_statuses() -> list[dict[str, str]]:
    """Transform documented ``Status`` members into template-ready rows.

    Members with no ``expectations`` and no ``actions`` are excluded
    from the docs table automatically.
    """
    rows = []
    for member in Status:
        level = member.value
        if not level.expectations and not level.actions:
            continue
        rows.append(
            {
                "label": _status_label(level),
                "message": _escape_cell(level.status.message),
                "expectations": _escape_cell(level.expectations),
                "actions": _escape_cell(level.actions),
            }
        )
    return rows


def _prepare_framework_statuses() -> list[dict[str, str]]:
    """Transform framework statuses into template-ready rows."""
    return [
        {
            "label": fw["status"],
            "message": _escape_cell(fw["message"]),
            "expectations": _escape_cell(fw["expectations"]),
            "actions": _escape_cell(fw["actions"]),
        }
        for fw in _FRAMEWORK_STATUSES
    ]


def _warn_undocumented() -> int:
    """Warn about members with no documentation prose.

    These are excluded from the docs table. The warning is informational
    only and does not break the build.
    """
    n = 0
    for member in Status:
        level = member.value
        if not level.expectations and not level.actions:
            print(
                f"WARNING: Status enum member '{member.name}' has no "
                f"expectations/actions — excluded from the docs table.",
                file=sys.stderr,
            )
            n += 1
    return n


def main() -> int:
    """Generate the statuses reference page.

    Returns 0 on success.
    """
    _warn_undocumented()

    n_total = len(list(Status))
    status_rows = _prepare_statuses()
    n_excluded = n_total - len(status_rows)
    framework_rows = _prepare_framework_statuses()

    _OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    page = _env.get_template("statuses.md.j2").render(
        description=(
            "Charmed Apache Kafka charm statuses reference - complete guide "
            "to Juju application statuses, messages, and troubleshooting "
            "actions."
        ),
        autogen_notice=_AUTOGEN_NOTICE,
        statuses=status_rows,
        framework_statuses=framework_rows,
    )
    out = _OUTPUT_DIR / "statuses.md"
    out.write_text(page, encoding="utf-8")

    print(
        f"Generated {out.relative_to(_REPO_ROOT)} "
        f"({len(status_rows)} shown, {n_excluded} excluded, "
        f"{len(framework_rows)} framework)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
