#!/usr/bin/env python3
# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.
"""Generate reference Markdown pages from charm source files.

Parses ``machine/actions.yaml`` and ``machine/config.yaml`` and renders
them through Jinja2 templates into ``docs/reference/_generated/``
(gitignored).  Runs as a pre-build step before Sphinx.

Usage::

    python3 docs/_dev/generate_charm_reference.py

Outputs::

    docs/reference/_generated/actions.md
    docs/reference/_generated/configurations.md
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import yaml
from jinja2 import Environment, FileSystemLoader

_SCRIPT_PATH = Path(__file__).resolve()
_DEV_DIR = _SCRIPT_PATH.parent
_DOCS_DIR = _DEV_DIR.parent
_REPO_ROOT = _DOCS_DIR.parent
_MACHINE_DIR = _REPO_ROOT / "machine"
_OUTPUT_DIR = _DOCS_DIR / "reference" / "_generated"
_TEMPLATES_DIR = _DEV_DIR / "templates"

_ACTIONS_FILE = _MACHINE_DIR / "actions.yaml"
_CONFIG_FILE = _MACHINE_DIR / "config.yaml"

_env = Environment(
    loader=FileSystemLoader(_TEMPLATES_DIR),
    keep_trailing_newline=True,
    trim_blocks=True,
    lstrip_blocks=True,
)


def _autogen_notice(source_file: str) -> str:
    """Build a per-page AUTO-GENERATED notice naming the exact source file."""
    return (
        f"<!-- AUTO-GENERATED. Do not edit this file directly. "
        f"Edit {source_file} and rebuild. -->"
    )


def load_yaml(path: Path) -> Any:
    """Load a YAML file and return its parsed content."""
    with path.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def _format_default(value: Any) -> str:
    """Format a default value for a Markdown table cell."""
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return f'`"{value}"`' if value == "" else f"`{value}`"
    return f"`{value}`"


def _format_text(value: Any) -> str:
    """Collapse whitespace in a description field for a table cell."""
    if value is None:
        return ""
    return " ".join(str(value).strip().split())


def _prepare_actions(data: dict[str, Any]) -> dict[str, Any]:
    """Transform raw YAML into template-ready data."""
    actions = {}
    for name, spec in data.items():
        if not isinstance(spec, dict):
            continue
        params = {}
        constraints = []
        for pname, pspec in (spec.get("params") or {}).items():
            if not isinstance(pspec, dict):
                continue
            enum = pspec.get("enum")
            minimum = pspec.get("minimum")
            params[pname] = {
                "type": pspec.get("type", ""),
                "default": _format_default(pspec.get("default")),
                "description": _format_text(pspec.get("description", "")),
                "enum": enum,
                "minimum": minimum,
            }
            if enum or minimum is not None:
                constraints.append(
                    {
                        "name": pname,
                        "enum": enum,
                        "minimum": minimum,
                    }
                )
        actions[name] = {
            "description": spec.get("description"),
            "params": params,
            "required": spec.get("required") or [],
            "additional_properties": spec.get("additionalProperties"),
            "constraints": constraints,
        }
    return {"actions": actions}


def _prepare_configurations(data: dict[str, Any]) -> dict[str, Any]:
    """Transform raw YAML into template-ready data."""
    options = {}
    for name, spec in (data.get("options") or {}).items():
        if not isinstance(spec, dict):
            continue
        options[name] = {
            "type": spec.get("type", ""),
            "default": _format_default(spec.get("default")),
            "description": _format_text(spec.get("description", "")),
        }
    return {"options": options}


def main() -> int:
    """Generate the reference pages.

    Returns 0 on success, 1 if a source file is missing.
    """
    if not _ACTIONS_FILE.exists():
        print(f"ERROR: actions file not found: {_ACTIONS_FILE}", file=sys.stderr)
        return 1
    if not _CONFIG_FILE.exists():
        print(f"ERROR: config file not found: {_CONFIG_FILE}", file=sys.stderr)
        return 1

    actions_data = load_yaml(_ACTIONS_FILE)
    config_data = load_yaml(_CONFIG_FILE)

    _OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    actions_ctx = _prepare_actions(actions_data)
    actions_ctx["description"] = (
        "Charmed Apache Kafka actions reference - complete list of juju "
        "actions with parameters, types, and defaults."
    )
    actions_ctx["autogen_notice"] = _autogen_notice("machine/actions.yaml")
    actions_md = _env.get_template("actions.md.j2").render(**actions_ctx)
    (_OUTPUT_DIR / "actions.md").write_text(actions_md, encoding="utf-8")

    config_ctx = _prepare_configurations(config_data)
    config_ctx["description"] = (
        "Charmed Apache Kafka configuration options reference - types, "
        "defaults, and descriptions for all config options."
    )
    config_ctx["autogen_notice"] = _autogen_notice("machine/config.yaml")
    config_md = _env.get_template("configurations.md.j2").render(**config_ctx)
    (_OUTPUT_DIR / "configurations.md").write_text(config_md, encoding="utf-8")

    print(
        f"Generated {(_OUTPUT_DIR / 'actions.md').relative_to(_REPO_ROOT)} "
        f"({len(actions_ctx['actions'])} actions)"
    )
    print(
        f"Generated {(_OUTPUT_DIR / 'configurations.md').relative_to(_REPO_ROOT)} "
        f"({len(config_ctx['options'])} config options)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
