# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  offsets-retention-minutes:
    description: the number of minutes offsets will be kept before getting discarded
    type: int
    default: 10080
  log-retention-hours:
    description: the number of hours to keep a log file before deleting it
    type: int
    default: 168
  auto-create-topics:
    description: enables auto creation of topic on the server
    type: boolean
    default: false
