{
 "title": "Kafka",
 "description": "Dashboard for Kafka and KRaft based on JMX Exporter",
 "tags": [
  "Kafka",
  "Stable",
  "KRaft"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},juju_unit)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_cluster_partition_replicascount{}, topic)"
   },
   {
    "name": "active_controller",
    "label": "Active Controller",
    "query": {
     "query": "query_result(kafka_controller_kafkacontroller_activecontrollercount == 1)"
    }
   },
   {
    "name": "brokers",
    "label": "Brokers",
    "query": {
     "query": "label_values(kafka_server_replicamanager_leadercount,juju_unit)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "description": "Number of brokers online",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (juju_model_uuid, juju_model) (kafka_server_replicamanager_leadercount{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (juju_model, juju_model_uuid) (kafka_controller_kafkacontroller_activecontrollercount{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total of Topics",
   "type": "stat",
   "description": "The total number of topics.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model) (kafka_controller_kafkacontroller_globaltopiccount{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$active_controller\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Replicas",
   "type": "stat",
   "description": "Number of replicas that are online.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model) (kafka_server_replicamanager_partitioncount{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model) (kafka_controller_kafkacontroller_offlinepartitionscount{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model) (kafka_server_replicamanager_underreplicatedpartitions{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitions at minimum ISR",
   "type": "stat",
   "description": "Number of partitions which are at their minimum in sync replica count (| ISR | == | min.insync.replicas |).",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model)(kafka_cluster_partition_atminisr{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitions under minimum ISR",
   "type": "stat",
   "description": "Number of partitions which are under their minimum in sync replica count (| ISR | < | min.insync.replicas |).",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model) (kafka_cluster_partition_underminisr{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Raft State",
   "type": "table",
   "description": "The role of the node in KRaft",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "max by (instance, juju_unit, juju_model, juju_model_uuid, state) (kafka_server_raft_metrics_current_state_info{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})"
    }
   ]
  },
  {
   "title": "Current Quorum Leader",
   "type": "timeseries",
   "description": "The current quorum leader's id for the cluster; -1 indicates unknown.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (juju_model, juju_model_uuid) (kafka_server_raft_metrics_current_leader{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Voted Leader",
   "type": "timeseries",
   "description": "The current voted leader's id for each kafka node; -1 indicates not voted for anyone.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (juju_model, juju_model_uuid, juju_unit) (kafka_server_raft_metrics_current_vote{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Quorum Epoch",
   "type": "timeseries",
   "description": "The current quorum epoch for the cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (juju_model, juju_model_uuid, juju_unit) (kafka_server_raft_metrics_current_epoch{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Append Metadata Records Rate",
   "type": "timeseries",
   "description": "The average number of records appended per second as the leader of the raft quorum.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (juju_model, juju_model_uuid, juju_unit) (kafka_server_raft_metrics_append_records_rate{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetch Metadata Records Rate",
   "type": "timeseries",
   "description": "The average number of records fetched from the leader of the raft quorum.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (juju_model, juju_model_uuid, juju_unit) (kafka_server_raft_metrics_fetch_records_rate{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metadata Records Commit Latency",
   "type": "timeseries",
   "description": "The average time in milliseconds to commit an entry in the raft log.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (juju_model, juju_model_uuid, juju_unit) (kafka_server_raft_metrics_commit_latency_avg{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitions Replicas Count Per Broker and Topic",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "kafka_cluster_partition_replicascount{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",topic=~\"$topic\"}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "In / Out Per Broker",
   "type": "timeseries",
   "description": "The in and out per broker for the cluster.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (juju_model, juju_model_uuid, juju_unit) (rate(kafka_server_brokertopicmetrics_bytesin_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "In: {juju_model_uuid={{juju_model_uuid}}, juju_model={{juju_model}}, juju_unit={{juju_unit}}}"
    },
    {
     "expr": "sum by (juju_model, juju_model_uuid, juju_unit) (rate(kafka_server_brokertopicmetrics_bytesout_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "Out: {juju_model_uuid={{juju_model_uuid}}, juju_model={{juju_model}}, juju_unit={{juju_unit}}}"
    }
   ]
  },
  {
   "title": "In / Out Per Topic",
   "type": "timeseries",
   "description": "The in and out per topic for the cluster.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, topic) (rate(kafka_server_brokertopicmetrics_bytesin_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "In: {juju_model_uuid={{juju_model_uuid}}, juju_model={{juju_model}}, topic={{topic}}}"
    },
    {
     "expr": "sum by (juju_model_uuid, juju_model, topic) (rate(kafka_server_brokertopicmetrics_bytesout_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "Out: {juju_model_uuid={{juju_model_uuid}}, juju_model={{juju_model}}, topic={{topic}}}"
    }
   ]
  },
  {
   "title": "Metadata Topic Incoming Bytes Rate",
   "type": "timeseries",
   "description": "The number of bytes read off all sockets per second.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, juju_unit) (rate(kafka_server_raft_channel_metrics_incoming_byte_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metadata Topic Outgoing Bytes Rate",
   "type": "timeseries",
   "description": "The number of outgoing bytes sent to all servers per second.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, juju_unit) (rate(kafka_server_raft_channel_metrics_outgoing_byte_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metadata Topic Requests Rate",
   "type": "timeseries",
   "description": "The number of requests sent per second.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, juju_unit) (rate(kafka_server_raft_channel_metrics_request_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metadata Topic Responses Rate",
   "type": "timeseries",
   "description": "The number of responses received per second.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, juju_unit) (rate(kafka_server_raft_channel_metrics_response_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Produce Request Rate Per Broker",
   "type": "timeseries",
   "description": "Produce request rate per broker.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (juju_model, juju_model_uuid, juju_unit) (rate(kafka_server_brokertopicmetrics_totalproducerequests_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetch Request Rate Per Broker",
   "type": "timeseries",
   "description": "Fetch request rate per broker.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, juju_unit) (rate(kafka_server_brokertopicmetrics_totalfetchrequests_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Produce Request Rate Per Topic",
   "type": "timeseries",
   "description": "Produce request rate per topic.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, topic) (irate(kafka_server_brokertopicmetrics_totalproducerequests_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetch Request Rate Per Topic",
   "type": "timeseries",
   "description": "Fetch request rate per topic",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, topic) (irate(kafka_server_brokertopicmetrics_totalfetchrequests_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",topic=~\"$topic\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Processor Avg Idle Percent",
   "type": "timeseries",
   "description": "Average percentage of time network processor is idle.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, juju_unit) (kafka_network_socketserver_networkprocessoravgidlepercent{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Handler Avg Idle Percent",
   "type": "timeseries",
   "description": "Average percentage of time request handler threads are idle.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, juju_unit) (kafka_server_kafkarequesthandlerpool_requesthandleravgidle_percent{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Produce Latency 99th Per Broker",
   "type": "timeseries",
   "description": "The 99th quantile of produce latency per broker.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (juju_model_uuid, juju_model, juju_unit) (kafka_network_requestmetrics_totaltimems{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",quantile=\"0.99\",request=\"Produce\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetch Consumer Latency 99th Per Broker",
   "type": "timeseries",
   "description": "The 99th quantile of fetch consumer latency per broker.",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (juju_model_uuid, juju_model, juju_unit) (kafka_network_requestmetrics_totaltimems{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",quantile=\"0.99\",request=\"FetchConsumer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetch Follow Latency 99th Per Broker",
   "type": "timeseries",
   "description": "The 99th quantile of fetch follow latency per broker.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (juju_model_uuid, juju_model, juju_unit) (kafka_network_requestmetrics_totaltimems{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",quantile=\"0.99\",request=\"FetchFollower\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Disk Writes",
   "type": "timeseries",
   "description": "Disk writes.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, juju_unit) (irate(kafka_server_kafkaserver_linux_disk_write_bytes{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "timeseries",
   "description": "Disk reads.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, juju_unit) (irate(kafka_server_kafkaserver_linux_disk_read_bytes{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Log Size By Broker (Disk Space Utilization)",
   "type": "timeseries",
   "description": "The log size for each broker.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, juju_unit) (kafka_log_log_size{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Log Size By Topic",
   "type": "timeseries",
   "description": "The log size for each topic.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, topic) (kafka_log_log_size{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$brokers\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Troubleshooting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 },
   "targets": [
    {}
   ]
  },
  {
   "title": "High Watermark",
   "type": "timeseries",
   "description": "The high watermark maintained on this member; -1 if it is unknown.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, juju_unit) (kafka_server_raft_metrics_high_watermark{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log End Offset",
   "type": "timeseries",
   "description": "The current raft log end offset.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, juju_unit) (kafka_server_raft_metrics_log_end_offset{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Produce Request Per Broker",
   "type": "timeseries",
   "description": "The failed produce request rate per broker.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, juju_unit) (rate(kafka_server_brokertopicmetrics_failedproducerequests_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Fetch Request Per Broker",
   "type": "timeseries",
   "description": "The failed fetch request rate per broker.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, juju_unit) (rate(kafka_server_brokertopicmetrics_failedfetchrequests_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$brokers\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Isr Shrinks / Isr Expands Per Second",
   "type": "timeseries",
   "description": "The in sync replicas shrinks and expand rate.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, juju_unit) (rate(kafka_server_replicamanager_isrshrink_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m]))",
     "legendFormat": "ISR Shrinks Per Second {juju_model_uuid={{juju_model_uuid}}, juju_molde={{juju_model}}}"
    },
    {
     "expr": "sum by (juju_model_uuid, juju_model, juju_unit) (rate(kafka_server_replicamanager_isrexpands_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m]))",
     "legendFormat": "ISR Expands Per Second {juju_model_uuid={{juju_model_uuid}}, juju_molde={{juju_model}}}"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "timeseries",
   "description": "The rate of kafka elects a new leader for a partition from replicas that are not part of the In-Sync Replica (ISR) set.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, juju_unit) (rate(kafka_controller_controllerstats_uncleanleaderelections_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Group Lags",
   "type": "timeseries",
   "description": "Total consumer offset lag summed across partitions, per consumer group and topic.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (group, topic) (sum by (group, topic, juju_unit) (kafka_consumer_offset_lag_total{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 183 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "description": "JVM Memory Used.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, juju_unit) (jvm_memory_bytes_used{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "timeseries",
   "description": "JVM GC Time.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, juju_unit) (rate(jvm_gc_collection_seconds_sum{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Thread Count",
   "type": "timeseries",
   "description": "JVM thread count.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 194 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, juju_unit) (jvm_threads_current{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM GC Count",
   "type": "timeseries",
   "description": "JVM GC Count.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 194 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (juju_model_uuid, juju_model, juju_unit) (jvm_gc_collection_seconds_count{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}