name: Markdown style checks

on:
  push:
    branches:
    - main
    paths:
    - 'docs/**'   # Only run on changes to the docs directory
  pull_request:
    branches:
    - '*'
    paths:
    - 'docs/**'   # Only run on changes to the docs directory
  workflow_dispatch:

jobs:
  markdown-lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: ubuntu-latest
      env:
        CONFIG: "docs/.sphinx/.markdownlint.json"
      run: |
        sudo apt install -y npm
        npm install markdownlint-cli2 --global
        markdownlint-cli2 --config "$CONFIG" "**/*.md"
