name: Markdown style checks

on:
  push:
    branches:
    - main
    paths:
    - 'docs/**'   # Only run on changes to the docs directory
  pull_request:
    branches:
    - '*'
    paths:
    - 'docs/**'   # Only run on changes to the docs directory
  workflow_call:
  workflow_dispatch:

jobs:
  markdown-lint:
    runs-on: ubuntu-22.04
    permissions: {}
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: "Run markdownlint"
      env:
        CONFIG: "docs/.sphinx/.markdownlint.json"
      run: |
        npm i markdownlint-cli2@0.16.0 --global
        markdownlint-cli2 --config "$CONFIG" "**/*.md"
